### ISSUE TITLE
scrape snapshot price

### ISSUE THREAD

**Issue by gabey9** [rodionlim/excel-stock-prices#1]
Can you make a function to scrape the snapshot price instead of previous close? Thanks.

**Comment by rodionlim** [comment]
@gabey9, I added the functionality to pull current price as well. There isn't a unique identifier to pull current price, so it might not be as stable as the other data points, but give it a try and let me know if it works for you.

**Comment by gabey9** [comment]
that works, thanks! I saw some people use 'span', class_='Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)' for getting the quote price

**Comment by gabey9** [comment]
one more request, would you please make a function to get Google Finance quote price "https://www.google.com/search?q={symbol}" Thank you.

**Comment by rodionlim** [comment]
Closing this issue since it has been resolved.
