### ISSUE TITLE
Extend function to get Google Finance quote price

### ISSUE THREAD

**Issue by rodionlim** [rodionlim/excel-stock-prices#2]
one more request, would you please make a function to get Google Finance quote price "https://www.google.com/search?q={symbol}" Thank you.

_Originally posted by @gabey9 in https://github.com/rodionlim/excel_stock_webscrape/issues/1#issuecomment-743997451_

**Comment by rodionlim** [comment]
@gabey9, is there anything that Google quotes have and Yahoo finance does not?

**Comment by gabey9** [comment]
some index data maybe, but mainly it's nice to have an alternative data source

**Comment by rodionlim** [comment]
Okay, sounds reasonable. I'll work on it when I have the time, going to keep this issue open for now

**Comment by rodionlim** [comment]
@gabey9 , you can test out the changes in [google-finance-api branch](https://github.com/rodionlim/excel_stock_webscrape/tree/google-finance-api)

**Comment by gabey9** [comment]
works perfectly, thanks!

**Comment by rodionlim** [comment]
Changes merged in master. Closing this issue.
